# Generated by Django 3.1 on 2021-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210313_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Tiếp nhận', 'Tiếp nhận'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='New', max_length=10),
        ),
    ]
